### ISSUE TITLE
ImportError: No module named matplotlib.image

### ISSUE THREAD

**Issue by opticyclic** [godfatherofpolka/ColorizationUsingOptimizationInPython#1]
You might want to mention the dependencies in the readme.
It is easier to install WinPython (256MB download!) than to download all the Matplot dependencies manually :(

**Comment by godfatherofpolka** [comment]
@opticyclic Thanks for the report. Unfortunately I do not have a Windows system to, but I will add a warning inthe readme. If you happen to be able to provide any detailled installation instructions for Windows, that would be great?

Also note that the matplotlib library is only used for the front end, colorizer.py, in order to read, save and display the image, the actual solver does not rely on it. There might be better alternatives for Windows to do this job, and it should be quite easy to change the code in order to adapt it?

(Also, I'm very sorry for the inconvenience, I know how annoying this kind of things can be. I do not have much experience with Python, and this tool was mainly written to play a bit with NumPy. If you have any good recommendation regarding Python dependencies, i.e., package management, etc. I will very gladly listen and learn.)
